### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by shakdwipeea** [shreyans4nahata/WhiteWalker#2]
Can u add a README with usage. I am planning to use this as rpc.

**Comment by shreyans4nahata** [comment]
@shakdwipeea is it ok now?

**Comment by shakdwipeea** [comment]
What features are implemented in this ?

**Comment by shreyans4nahata** [comment]
@shakdwipeea  few features are:
- Listing of billboard UK top 40 songs.
- Download of the Audio or Video of any song or video on youtube.
- Chrome extension for downloading audio.
- Download from terminal using the script.

Same is now reflected in the readme file.( I think this is what you asked. If not please do clarify.)

**Comment by shakdwipeea** [comment]
Instructions to use the chrome extension?

**Comment by shreyans4nahata** [comment]
Updated readme file.
@shakdwipeea  Please see [this](https://github.com/shreyans4nahata/WhiteWalker/issues/5)
